package org.drools.vertx.demo.cep.rules;

import org.drools.vertx.demo.cep.model.FlightInfoEvent;
import org.drools.vertx.demo.cep.model.LuggageScanEvent;
import java.io.Serializable;
import org.drools.vertx.demo.cep.command.Command;

global org.drools.vertx.demo.cep.command.CommandFactory commandFactory;
global org.drools.vertx.demo.cep.model.FlightInfoEvent flightInfo;

rule "Flight Info Update"
when
	$f: FlightInfoEvent()
then
	//channels["VertxChannel"].send(commandFactory.getSystemOutCommand("Baggage lost at sorting. BagTag ID: " + $b1.getBagTag().getId(), drools));
	channels["VertxChannel"].send(commandFactory.buildCommand((Command & Serializable)() -> {
		System.out.println("Flight info update: " + $f.getFlightCode());
	}));
end

rule "Luggage Scanned"
when
	$ls: LuggageScanEvent()
then
	channels["VertxChannel"].send(commandFactory.buildCommand((Command & Serializable)() -> {
		System.out.println("Luggage scanned for flight: " + flightInfo.getFlightCode());
	}));
end


